import type { Doctor, DoctorProfile } from "@/components/doctor-card"

export const mockDoctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    rating: 4.9,
    reviewCount: 127,
    location: "Downtown Medical Center",
    distance: "2.3 miles",
    nextAvailable: "Today at 3:00 PM",
    image: "/female-doctor-professional.jpg",
    experience: "15 years",
    acceptingNew: true,
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    specialty: "Dermatologist",
    rating: 4.8,
    reviewCount: 94,
    location: "Skin Health Clinic",
    distance: "1.8 miles",
    nextAvailable: "Tomorrow at 10:00 AM",
    image: "/professional-male-doctor.png",
    experience: "12 years",
    acceptingNew: true,
  },
  {
    id: "3",
    name: "Dr. Emily Rodriguez",
    specialty: "Pediatrician",
    rating: 5.0,
    reviewCount: 203,
    location: "Children's Health Center",
    distance: "3.1 miles",
    nextAvailable: "Today at 5:30 PM",
    image: "/female-pediatrician.png",
    experience: "18 years",
    acceptingNew: false,
  },
  {
    id: "4",
    name: "Dr. James Wilson",
    specialty: "Dentist",
    rating: 4.7,
    reviewCount: 156,
    location: "Bright Smile Dental",
    distance: "0.9 miles",
    nextAvailable: "Tomorrow at 2:00 PM",
    image: "/male-dentist-professional.png",
    experience: "10 years",
    acceptingNew: true,
  },
  {
    id: "5",
    name: "Dr. Lisa Anderson",
    specialty: "Psychiatrist",
    rating: 4.9,
    reviewCount: 88,
    location: "Mental Wellness Center",
    distance: "4.2 miles",
    nextAvailable: "Next Monday at 9:00 AM",
    image: "/female-psychiatrist-professional.jpg",
    experience: "20 years",
    acceptingNew: true,
  },
  {
    id: "6",
    name: "Dr. Robert Martinez",
    specialty: "Orthopedic",
    rating: 4.8,
    reviewCount: 142,
    location: "Sports Medicine Institute",
    distance: "5.5 miles",
    nextAvailable: "This Friday at 11:00 AM",
    image: "/male-orthopedic-doctor.png",
    experience: "16 years",
    acceptingNew: true,
  },
]

export const mockDoctorProfiles: Record<string, DoctorProfile> = {
  "1": {
    id: "1",
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    image: "/female-doctor-professional.jpg",
    rating: 4.9,
    reviewCount: 127,
    location: "Downtown Medical Center, 123 Main St",
    experience: "15 years",
    education: "MD from Harvard Medical School",
    languages: ["English", "Spanish"],
    acceptingNew: true,
    about:
      "Dr. Sarah Johnson is a board-certified cardiologist with over 15 years of experience in treating heart conditions. She specializes in preventive cardiology and has helped hundreds of patients improve their heart health through personalized treatment plans.",
    specializations: ["Preventive Cardiology", "Heart Disease", "Hypertension", "Cholesterol Management"],
  },
  "2": {
    id: "2",
    name: "Dr. Michael Chen",
    specialty: "Dermatologist",
    image: "/professional-male-doctor.png",
    rating: 4.8,
    reviewCount: 94,
    location: "Skin Health Clinic, 456 Oak Ave",
    experience: "12 years",
    education: "MD from Stanford University",
    languages: ["English", "Mandarin"],
    acceptingNew: true,
    about:
      "Dr. Michael Chen is a skilled dermatologist specializing in both medical and cosmetic dermatology. He is known for his gentle approach and expertise in treating various skin conditions.",
    specializations: ["Acne Treatment", "Skin Cancer Screening", "Cosmetic Dermatology", "Eczema"],
  },
  "3": {
    id: "3",
    name: "Dr. Emily Rodriguez",
    specialty: "Pediatrician",
    image: "/female-pediatrician.png",
    rating: 5.0,
    reviewCount: 203,
    location: "Children's Health Center, 789 Elm St",
    experience: "18 years",
    education: "MD from Johns Hopkins University",
    languages: ["English", "Spanish", "Portuguese"],
    acceptingNew: false,
    about:
      "Dr. Emily Rodriguez is a compassionate pediatrician dedicated to providing comprehensive care for children from infancy through adolescence. Parents trust her expertise and warm bedside manner.",
    specializations: ["Well-Child Visits", "Vaccinations", "Developmental Assessments", "Pediatric Nutrition"],
  },
  "4": {
    id: "4",
    name: "Dr. James Wilson",
    specialty: "Dentist",
    image: "/male-dentist-professional.png",
    rating: 4.7,
    reviewCount: 156,
    location: "Bright Smile Dental, 321 Pine St",
    experience: "10 years",
    education: "DDS from UCLA School of Dentistry",
    languages: ["English"],
    acceptingNew: true,
    about:
      "Dr. James Wilson is committed to helping patients achieve optimal oral health. He uses the latest dental technology and techniques to provide comfortable, effective treatments.",
    specializations: ["General Dentistry", "Cosmetic Dentistry", "Teeth Whitening", "Dental Implants"],
  },
  "5": {
    id: "5",
    name: "Dr. Lisa Anderson",
    specialty: "Psychiatrist",
    image: "/female-psychiatrist-professional.jpg",
    rating: 4.9,
    reviewCount: 88,
    location: "Mental Wellness Center, 555 Maple Dr",
    experience: "20 years",
    education: "MD from Yale School of Medicine",
    languages: ["English", "French"],
    acceptingNew: true,
    about:
      "Dr. Lisa Anderson is an experienced psychiatrist specializing in anxiety, depression, and mood disorders. She takes a holistic approach to mental health, combining medication management with therapy.",
    specializations: ["Anxiety Disorders", "Depression", "Bipolar Disorder", "PTSD"],
  },
  "6": {
    id: "6",
    name: "Dr. Robert Martinez",
    specialty: "Orthopedic",
    image: "/male-orthopedic-doctor.png",
    rating: 4.8,
    reviewCount: 142,
    location: "Sports Medicine Institute, 888 Cedar Ln",
    experience: "16 years",
    education: "MD from Duke University",
    languages: ["English", "Spanish"],
    acceptingNew: true,
    about:
      "Dr. Robert Martinez is a board-certified orthopedic surgeon with extensive experience in sports medicine and joint replacement. He has helped countless athletes and active individuals return to their favorite activities.",
    specializations: ["Sports Injuries", "Joint Replacement", "Arthroscopy", "Fracture Care"],
  },
}
